/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package yatzy;
import java.util.ArrayList;
/**
 *
 * @author johnh
 */
public class YatzyJFrame extends javax.swing.JFrame {
    //en boolean för att låsa tärningarna
    boolean las1 = true, las2 = true, las3 = true, las4 = true, las5 = true;
    
    //räknare för antalkast
    int antalKast = 3;
    
    //räknare för poängsumma
    int totalSumma = 0;
    
    //räknare för poäng första delen
    int poang = 0;
    
    //räknare för bonus
    int bonus;
    
    //lista för tärningsresultat
    int tarningLista[] = new int[5];
    
    //en räknare där varje index är ett möjligt resultat. Index 1 = antal ettor,
    //index 2 = antal tvåor osv. Index 1-6 = sida 1-6, index 0 används ej
    int[] tarningarResultatLista = new int[7];
        
        
    /**
     * Creates new form YatzyJFrame
     */
    public YatzyJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnKasta = new javax.swing.JButton();
        btnDice1 = new javax.swing.JToggleButton();
        btnDice2 = new javax.swing.JToggleButton();
        btnDice3 = new javax.swing.JToggleButton();
        btnDice4 = new javax.swing.JToggleButton();
        btnDice5 = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnEttor = new javax.swing.JButton();
        btnTreor = new javax.swing.JButton();
        btnTvaor = new javax.swing.JButton();
        btnFemmor = new javax.swing.JButton();
        btnFyror = new javax.swing.JButton();
        btnSexor = new javax.swing.JButton();
        txfEttor = new javax.swing.JTextField();
        txfTvaor = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        txfFyror = new javax.swing.JTextField();
        txfTreor = new javax.swing.JTextField();
        txfFemmor = new javax.swing.JTextField();
        txfSexor = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txfSumma = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        btnStarta = new javax.swing.JButton();
        lblKast = new javax.swing.JLabel();
        btnPar = new javax.swing.JButton();
        btnTvapar = new javax.swing.JButton();
        btnYatzy = new javax.swing.JButton();
        btnTriss = new javax.swing.JButton();
        btnStorstege = new javax.swing.JButton();
        btnFyrtal = new javax.swing.JButton();
        btnLitenstege = new javax.swing.JButton();
        btnKak = new javax.swing.JButton();
        btnChans = new javax.swing.JButton();
        txfPar = new javax.swing.JTextField();
        txfTvapar = new javax.swing.JTextField();
        txfTriss = new javax.swing.JTextField();
        txfFyrtal = new javax.swing.JTextField();
        txfKak = new javax.swing.JTextField();
        txfLitenstege = new javax.swing.JTextField();
        txfStorstege = new javax.swing.JTextField();
        txfChans = new javax.swing.JTextField();
        txfYatzy = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txfPoang = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Yatzy");

        btnKasta.setText("Kasta tärningar");
        btnKasta.setEnabled(false);
        btnKasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKastaActionPerformed(evt);
            }
        });

        btnDice1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDice1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDice1ActionPerformed(evt);
            }
        });

        btnDice2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDice2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDice2ActionPerformed(evt);
            }
        });

        btnDice3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDice3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDice3ActionPerformed(evt);
            }
        });

        btnDice4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDice4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDice4ActionPerformed(evt);
            }
        });

        btnDice5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDice5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDice5ActionPerformed(evt);
            }
        });

        jLabel2.setText("Antal spelare:");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "En spelare", "Två spelare" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        btnEttor.setText("Ettor");
        btnEttor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEttorActionPerformed(evt);
            }
        });

        btnTreor.setText("Treor");
        btnTreor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTreorActionPerformed(evt);
            }
        });

        btnTvaor.setText("Tvåor");
        btnTvaor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTvaorActionPerformed(evt);
            }
        });

        btnFemmor.setText("Femmor");
        btnFemmor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFemmorActionPerformed(evt);
            }
        });

        btnFyror.setText("Fyror");
        btnFyror.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFyrorActionPerformed(evt);
            }
        });

        btnSexor.setText("Sexor");
        btnSexor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSexorActionPerformed(evt);
            }
        });

        txfEttor.setEditable(false);

        txfTvaor.setEditable(false);

        jTextField3.setEditable(false);

        jTextField4.setEditable(false);

        jTextField5.setEditable(false);

        jTextField6.setEditable(false);

        jTextField7.setEditable(false);

        txfFyror.setEditable(false);

        txfTreor.setEditable(false);

        txfFemmor.setEditable(false);

        txfSexor.setEditable(false);
        txfSexor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSexorActionPerformed(evt);
            }
        });

        jTextField12.setEditable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Poäng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        jLabel3.setText("Total Summa");

        txfSumma.setEditable(false);
        txfSumma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfSummaActionPerformed(evt);
            }
        });

        jTextField16.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(35, 35, 35)
                .addComponent(txfSumma, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txfSumma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        btnStarta.setText("Starta spelet");
        btnStarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartaActionPerformed(evt);
            }
        });

        lblKast.setText("Kast kvar: ");

        btnPar.setText("Par");
        btnPar.setPreferredSize(new java.awt.Dimension(81, 25));
        btnPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnParActionPerformed(evt);
            }
        });

        btnTvapar.setText("Tvåpar");
        btnTvapar.setPreferredSize(new java.awt.Dimension(81, 25));
        btnTvapar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTvaparActionPerformed(evt);
            }
        });

        btnYatzy.setText("Yatzy");
        btnYatzy.setPreferredSize(new java.awt.Dimension(81, 25));
        btnYatzy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnYatzyActionPerformed(evt);
            }
        });

        btnTriss.setText("Triss");
        btnTriss.setPreferredSize(new java.awt.Dimension(81, 25));
        btnTriss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrissActionPerformed(evt);
            }
        });

        btnStorstege.setText("Stor stege");
        btnStorstege.setPreferredSize(new java.awt.Dimension(81, 25));
        btnStorstege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStorstegeActionPerformed(evt);
            }
        });

        btnFyrtal.setText("Fyrtal");
        btnFyrtal.setPreferredSize(new java.awt.Dimension(81, 25));
        btnFyrtal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFyrtalActionPerformed(evt);
            }
        });

        btnLitenstege.setText("Liten stege");
        btnLitenstege.setPreferredSize(new java.awt.Dimension(81, 25));
        btnLitenstege.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLitenstegeActionPerformed(evt);
            }
        });

        btnKak.setText("Kåk");
        btnKak.setPreferredSize(new java.awt.Dimension(81, 25));
        btnKak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKakActionPerformed(evt);
            }
        });

        btnChans.setText("Chans");
        btnChans.setPreferredSize(new java.awt.Dimension(81, 25));
        btnChans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChansActionPerformed(evt);
            }
        });

        txfPar.setEditable(false);

        txfTvapar.setEditable(false);

        txfTriss.setEditable(false);

        txfFyrtal.setEditable(false);

        txfKak.setEditable(false);

        txfLitenstege.setEditable(false);

        txfStorstege.setEditable(false);

        txfChans.setEditable(false);

        txfYatzy.setEditable(false);

        jTextField21.setEditable(false);

        jTextField22.setEditable(false);

        jTextField23.setEditable(false);

        jTextField24.setEditable(false);

        jTextField25.setEditable(false);

        jTextField26.setEditable(false);

        jTextField27.setEditable(false);

        jTextField28.setEditable(false);

        jTextField29.setEditable(false);

        jLabel5.setText("(50 bonuspoäng om man får över 62 poäng)");

        jLabel6.setText("Klicka på en tärning för att spara, klicka igen för att låsa upp");

        jLabel4.setText("Bonus");

        jTextField13.setEditable(false);
        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });

        jTextField15.setEditable(false);

        jLabel7.setText("Poäng");

        txfPoang.setEditable(false);

        jTextField1.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(btnStarta))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(btnDice1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(btnDice2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSexor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFemmor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFyror, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTvaor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTreor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEttor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfEttor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfSexor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfFemmor, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txfFyror, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txfTreor, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                                    .addComponent(txfTvaor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfPoang)
                            .addComponent(jTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                            .addComponent(jTextField15))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnPar, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                    .addComponent(btnTvapar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTriss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnFyrtal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfTvapar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfTriss, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfFyrtal, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfPar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnKak, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                                    .addComponent(btnLitenstege, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfLitenstege, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfKak, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btnDice3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDice4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnDice5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKast, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnKasta))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnStorstege, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnChans, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfStorstege, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txfChans, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnYatzy, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txfYatzy, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDice3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(btnDice1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDice2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDice4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDice5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnStarta))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(btnKasta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblKast)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEttor)
                    .addComponent(txfEttor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfPar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTvaor)
                    .addComponent(txfTvaor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTvapar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfTvapar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTreor)
                    .addComponent(txfTreor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTriss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfTriss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfFyror, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFyrtal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfFyrtal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnKak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfKak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLitenstege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfLitenstege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txfStorstege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnStorstege, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnChans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfChans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnYatzy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfYatzy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnFyror)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnFemmor)
                            .addComponent(txfFemmor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSexor)
                            .addComponent(txfSexor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txfPoang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        getAccessibleContext().setAccessibleParent(jScrollPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKastaActionPerformed
        //anropa metoden för att kasta tärningar som inte är låsta
        if(antalKast > 0){
            kastaTarning();
        
            //räkna ner antal kast
            antalKast--;
            lblKast.setText("Kast kvar: " + String.valueOf(antalKast));
        }
        
        
        //spara alla resultat i en lista
        tarningLista[0] = Integer.valueOf(btnDice1.getText());
        tarningLista[1] = Integer.valueOf(btnDice2.getText());
        tarningLista[2] = Integer.valueOf(btnDice3.getText());
        tarningLista[3] = Integer.valueOf(btnDice4.getText());
        tarningLista[4] = Integer.valueOf(btnDice5.getText());
        
        //nollställ listan
        for (int i = 0; i < tarningarResultatLista.length; i++) {
            tarningarResultatLista[i] = 0;
        }
        //räkna antal resultat
        for (int i = 0; i < tarningLista.length; i++) {
            //spara värdet på tarningen (från plats i) som en int
            int sidaTarning = tarningLista[i];
            //öka index på rätt plats för att öka antalet av den aktuella sidan
            //t ex om index 2 ökar till 3 så finns det tre tvåor
            tarningarResultatLista[sidaTarning]++;
        }
        
        //Om antal kast kvar är noll så stäng av knappen
        if(antalKast == 0){
            btnKasta.setEnabled(false);
        }
        
    }//GEN-LAST:event_btnKastaActionPerformed

    private void btnDice1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDice1ActionPerformed
        //tryck på knappen för att låsa tärningen
        if (las1){
            las1 = false;
        }
        else{
            las1 = true;
        }
    }//GEN-LAST:event_btnDice1ActionPerformed

    private void btnDice2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDice2ActionPerformed
        //tryck på knappen för att låsa tärningen
        if (las2){
            las2 = false;
        }
        else{
            las2 = true;
        }
    }//GEN-LAST:event_btnDice2ActionPerformed

    private void btnDice3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDice3ActionPerformed
        //tryck på knappen för att låsa tärningen
        if (las3){
            las3 = false;
        }
        else{
            las3 = true;
        }
    }//GEN-LAST:event_btnDice3ActionPerformed

    private void btnDice4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDice4ActionPerformed
        //tryck på knappen för att låsa tärningen
        if (las4){
            las4 = false;
        }
        else{
            las4 = true;
        }
    }//GEN-LAST:event_btnDice4ActionPerformed

    private void btnDice5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDice5ActionPerformed
        //tryck på knappen för att låsa tärningen
        if (las5){
            las5 = false;
        }
        else{
            las5 = true;
        }
    }//GEN-LAST:event_btnDice5ActionPerformed

    private void btnStartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartaActionPerformed
        //stäng av startaknappen
        btnStarta.setEnabled(false);
        nyRunda();
    }//GEN-LAST:event_btnStartaActionPerformed

    private void btnEttorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEttorActionPerformed
        txfEttor.setText(String.valueOf(siffraTarning(1, tarningLista)));
        btnEttor.setEnabled(false);
    }//GEN-LAST:event_btnEttorActionPerformed

    private void txfSummaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfSummaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfSummaActionPerformed

    private void btnTvaorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTvaorActionPerformed
        txfTvaor.setText(String.valueOf(siffraTarning(2, tarningLista)));
        btnTvaor.setEnabled(false);
    }//GEN-LAST:event_btnTvaorActionPerformed

    private void btnTreorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTreorActionPerformed
        txfTreor.setText(String.valueOf(siffraTarning(3, tarningLista)));
        btnTreor.setEnabled(false);
    }//GEN-LAST:event_btnTreorActionPerformed

    private void btnFyrorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFyrorActionPerformed
        txfFyror.setText(String.valueOf(siffraTarning(4, tarningLista)));
        btnFyror.setEnabled(false);
    }//GEN-LAST:event_btnFyrorActionPerformed

    private void btnFemmorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFemmorActionPerformed
        txfFemmor.setText(String.valueOf(siffraTarning(5, tarningLista)));
        btnFemmor.setEnabled(false);
    }//GEN-LAST:event_btnFemmorActionPerformed

    private void txfSexorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfSexorActionPerformed
        
    }//GEN-LAST:event_txfSexorActionPerformed

    private void btnSexorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSexorActionPerformed
        txfSexor.setText(String.valueOf(siffraTarning(6, tarningLista)));
        btnSexor.setEnabled(false);
    }//GEN-LAST:event_btnSexorActionPerformed

    private void btnTrissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrissActionPerformed
        //skapa en summa för triss och anropa metod för att leta upp poäng
        int summaTriss = letaKombo(3, tarningarResultatLista);
        
        //visa poäng summaPar
        txfTriss.setText(String.valueOf(summaTriss));
        
        //öka totalpoängen
        txfSumma.setText(String.valueOf(totalSumma += summaTriss));
        
        //stäng av knappen
        btnTriss.setEnabled(false);
        
        nyRunda();
    }//GEN-LAST:event_btnTrissActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void btnParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnParActionPerformed
        //skapa en summa för par och anropa metod för att leta upp poäng
        int summaPar = letaKombo(2, tarningarResultatLista);
      
        //visa poäng summaPar
        txfPar.setText(String.valueOf(summaPar));
        
        //öka totalpoängen
        txfSumma.setText(String.valueOf(totalSumma += summaPar));
        
        btnPar.setEnabled(false);
        
        nyRunda();
    }//GEN-LAST:event_btnParActionPerformed

    private void btnChansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChansActionPerformed
        //räkna ut totala summan av alla tärningar som visas
        int chans = 0;
        for (int i = 0; i < tarningLista.length; i++) {
            txfSumma.setText(String.valueOf(totalSumma += tarningLista[i]));
            txfChans.setText(String.valueOf(chans += tarningLista[i]));
        }
        
        btnChans.setEnabled(false);
        
        nyRunda();
        
    }//GEN-LAST:event_btnChansActionPerformed

    private void btnYatzyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnYatzyActionPerformed
        //ta in värdet på första platsen i listan
        int tarning1 = tarningLista[0];
        //räkna antal samma sidor
        int sammaSida = 0;
        for (int i = 0; i < tarningLista.length; i++) {
            //Om någon annan plats i listan har ett annat värde än tarning1 så avbryt
            if (tarning1 != tarningLista[i]){
                break;
            }
            //Om något har samma värde ge 50 poäng
            else{
                sammaSida++;
            }
        }
        //om antal sammaSida är lika med längden på tarningLista (5) så ge 50 poäng
        if (sammaSida == tarningLista.length){
            txfSumma.setText(String.valueOf(totalSumma += 50));
            txfYatzy.setText("50");
        }
        //annars ge 0 poäng
        else {
            txfYatzy.setText("0");
        }
        
        btnYatzy.setEnabled(false);
        
        nyRunda();
    }//GEN-LAST:event_btnYatzyActionPerformed

    private void btnTvaparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTvaparActionPerformed
        //skapa en summa för par och anropa metod för att leta upp poäng
        int summaParEtt = letaKombo(2, tarningarResultatLista);
        
        int summaParTva = 0;
        
        //en int för att hitta olika par
        int ejSummaParEtt = summaParEtt/2; 
        for (int i = 1; i < tarningarResultatLista.length; i++) {
            //spara summan på par 2 om det finns ett till par som inte är samma
            //som det första paret
            if (i != ejSummaParEtt && tarningarResultatLista[i] >= 2){
                summaParTva = i * 2;
            }
        }
        //skapa poäng för tvåpar
        int summaTvapar = 0;
        //om något av paren = 0 så får man inga poäng
        if (summaParEtt != 0 && summaParTva != 0){
            summaTvapar = summaParEtt + summaParTva;
        }
        //visa poäng summaPar
        txfTvapar.setText(String.valueOf(summaTvapar));
        
        //öka totalpoängen
        txfSumma.setText(String.valueOf(totalSumma += summaTvapar));
        
        btnTvapar.setEnabled(false);
        
        nyRunda();
    }//GEN-LAST:event_btnTvaparActionPerformed

    private void btnFyrtalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFyrtalActionPerformed
        //skapa en summa för fyrtal och anropa metod för att leta upp poäng
        int summaFyrtal = letaKombo(4, tarningarResultatLista);
        
        //visa poäng summaPar
        txfFyrtal.setText(String.valueOf(summaFyrtal));
        
        //öka totalpoängen
        txfSumma.setText(String.valueOf(totalSumma += summaFyrtal));
        
        //stäng av knappen
        btnFyrtal.setEnabled(false);
        
        nyRunda();
    }//GEN-LAST:event_btnFyrtalActionPerformed

    private void btnKakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKakActionPerformed
        //skapa en summa för triss och anropa metod för att leta upp poäng
        int summaTriss = letaKombo(3, tarningarResultatLista);
        
        //skapa en summa för par
        int summaPar = 0;
        
        //en loop som går igenom listan med antal sparade värden
        for (int i = 1; i < tarningarResultatLista.length; i++) {
            //om något av de sparade värdena är EXAKT lika med 2 så öka poängsumman för par
            //med sida * 2
            if (tarningarResultatLista[i] == 2){
                summaPar = i * 2;
            }
        }
        
        //skapa en summa för kåk
        int summaKak = 0;
        //om paret eller trissen ger 0 i summa så får man inga poäng
        if (summaPar != 0 && summaTriss != 0){
            summaKak = summaPar + summaTriss;
        }
        //visa poäng summaPar
        txfKak.setText(String.valueOf(summaKak));
        
        //öka totalpoängen
        txfSumma.setText(String.valueOf(totalSumma += summaKak));
        
        //stäng av knappen
        btnKak.setEnabled(false);
        
        nyRunda();
    }//GEN-LAST:event_btnKakActionPerformed

    private void btnLitenstegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLitenstegeActionPerformed
        //villkor för att se om litenstege finns eller ej
        boolean litenStege = true;
        
        //en loop som går igenom söker igenom alla tärningar efter siffrorna 1-5.
        for (int i = 1; i <= 5; i++) {
            //sekventiell sökning efter siffran i
            //om siffran i inte finns på någon tärning så avbryts loopen och
            //litenStege sätt till false
            if (sekventiellSokning(tarningLista, i) == -1){
                litenStege = false;
                break;
            }
        }
        
        //om litenStege är true så får man 15 poäng (1+2+3+4+5)
        if(litenStege){
            txfLitenstege.setText(String.valueOf(15));
            txfSumma.setText(String.valueOf(totalSumma+=15));
        }
        //annars inga poäng
        else{
            txfLitenstege.setText("0");
        }
        
        btnLitenstege.setEnabled(false);
        nyRunda();
        
    }//GEN-LAST:event_btnLitenstegeActionPerformed

    private void btnStorstegeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStorstegeActionPerformed
        //villkor för att se om stor stege finns eller ej
        boolean storStege = true;
        
        //en loop som går igenom söker igenom alla tärningar efter siffrorna 2-6.
        for (int i = 2; i <= 6; i++) {
            //sekventiell sökning efter siffran i
            //om siffran i inte finns på någon tärning så avbryts loopen och
            //storStege sätt till false
            if (sekventiellSokning(tarningLista, i) == -1){
                storStege = false;
                break;
            }
        }
        
        //om storStege är true så får man 20 poäng (2+3+4+5+6)
        if(storStege){
            txfStorstege.setText(String.valueOf(20));
            txfSumma.setText(String.valueOf(totalSumma+=20));
        }
        //annars inga poäng
        else{
            txfStorstege.setText("0");
        }
        
        btnStorstege.setEnabled(false);
        
        nyRunda();
    }//GEN-LAST:event_btnStorstegeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(YatzyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(YatzyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(YatzyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(YatzyJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new YatzyJFrame().setVisible(true);
            }
        });
    }
    
        /**
         * En metod som rullar alla olåsta tärningar
         */
    public void kastaTarning(){
        if(las1){
            btnDice1.setText(String.valueOf((int)(Math.random()*6)+1));
        }
        if(las2){
            btnDice2.setText(String.valueOf((int)(Math.random()*6)+1));
        }
        if(las3){
        btnDice3.setText(String.valueOf((int)(Math.random()*6)+1));
        }
        if(las4){
            btnDice4.setText(String.valueOf((int)(Math.random()*6)+1));
        }
        if(las5){
        btnDice5.setText(String.valueOf((int)(Math.random()*6)+1));
        }
    }
    
    /**
     * ge spelaren 3 kast, starta kastaknappen, töm alla tärningar och
     * nollställ listorna
     */
    public void nyRunda(){
        btnKasta.setEnabled(true);
        antalKast = 3;
        lblKast.setText("Kast kvar: " + String.valueOf(antalKast));
        
        //ta bort siffrorna på tärningsknapparna
        btnDice1.setText("");
        btnDice2.setText("");
        btnDice3.setText("");
        btnDice4.setText("");
        btnDice5.setText("");
        
        
        //nollställ listan
        for (int i = 0; i < tarningarResultatLista.length; i++) {
            tarningarResultatLista[i] = 0;
        }
    }
    
    /**
     * räknar alla tärningnar med efterfrågad valör
     * @param siffraTarning efterfrågad valör på tärningen
     */
    public int siffraTarning(int siffraTarning, int[] tarningLista){
        //skapa en summa
        int summa = 0;
        
        //leta efter efterfrågad siffra och öka summan med valör "tärning" varje gång den finns
        for (int i = 0; i < tarningLista.length; i++) {
            if(tarningLista[i] == siffraTarning){
                summa += siffraTarning;
            }
        }
        
        //Uppdatera totalsumman
        totalSumma +=summa;
        
        //skriv ut totalsumman
        txfSumma.setText(String.valueOf(totalSumma));
        
        //skriv in poäng för första delen
        txfPoang.setText(String.valueOf(poang+=summa));
        
        //börja ny runda
        nyRunda();
        
        //öka bonus
        bonus += summa;
        //kolla om bonus är över 62, i så fall ge 50 extra poäng
        if (bonus >62 ){
            txfSumma.setText(String.valueOf(totalSumma += 50));
        }
        
        //Skicka tillbaka poäng för aktuell rad
        return summa;
    }
    /**
     * 
     * @param kombo den typ av kombination som letas efter (par, triss, fyrtal)
     * @param tarningarResultatLista listan med resultat
     * @return poängsumman på par/triss/fyrtal
     */
    public int letaKombo(int kombo, int[] tarningarResultatLista){
        //skapa en int med poäng
        int summaKombo = 0;
        
        //en loop som går igenom listan med antal sparade värden
        for (int i = 1; i < tarningarResultatLista.length; i++) {
            /*om något av de sparade värdena är över eller lika med kombo
            *(kombo = par/triss/fyrtal = 2, 3, 4)
            *så öka poängsumman för par med sida * kombo
            */
            if (tarningarResultatLista[i] >= kombo){
                summaKombo = i * kombo;
                
            }
        }
        return summaKombo;
    }
    public int sekventiellSokning(int[] tarningLista, int sokVarde){
        int index = -1;
        
        for (int i = 0; i < tarningLista.length; i++) {
            if (tarningLista[i] == sokVarde){
                index = i;
                break;
            }
        }
        return index;
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChans;
    private javax.swing.JToggleButton btnDice1;
    private javax.swing.JToggleButton btnDice2;
    private javax.swing.JToggleButton btnDice3;
    private javax.swing.JToggleButton btnDice4;
    private javax.swing.JToggleButton btnDice5;
    private javax.swing.JButton btnEttor;
    private javax.swing.JButton btnFemmor;
    private javax.swing.JButton btnFyror;
    private javax.swing.JButton btnFyrtal;
    private javax.swing.JButton btnKak;
    private javax.swing.JButton btnKasta;
    private javax.swing.JButton btnLitenstege;
    private javax.swing.JButton btnPar;
    private javax.swing.JButton btnSexor;
    private javax.swing.JButton btnStarta;
    private javax.swing.JButton btnStorstege;
    private javax.swing.JButton btnTreor;
    private javax.swing.JButton btnTriss;
    private javax.swing.JButton btnTvaor;
    private javax.swing.JButton btnTvapar;
    private javax.swing.JButton btnYatzy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JLabel lblKast;
    private javax.swing.JTextField txfChans;
    private javax.swing.JTextField txfEttor;
    private javax.swing.JTextField txfFemmor;
    private javax.swing.JTextField txfFyror;
    private javax.swing.JTextField txfFyrtal;
    private javax.swing.JTextField txfKak;
    private javax.swing.JTextField txfLitenstege;
    private javax.swing.JTextField txfPar;
    private javax.swing.JTextField txfPoang;
    private javax.swing.JTextField txfSexor;
    private javax.swing.JTextField txfStorstege;
    private javax.swing.JTextField txfSumma;
    private javax.swing.JTextField txfTreor;
    private javax.swing.JTextField txfTriss;
    private javax.swing.JTextField txfTvaor;
    private javax.swing.JTextField txfTvapar;
    private javax.swing.JTextField txfYatzy;
    // End of variables declaration//GEN-END:variables
}
